name: Deploy Eleventy Site

on:
  push:
    branches: [ main ]
    paths-ignore:
      - .github

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Install pnpm
      uses: pnpm/action-setup@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'pnpm'
 
    - name: Install dependencies
      run: pnpm install
    
    - name: Build site
      run: pnpm build
    
    - name: Deploy to server
      if: github.ref == 'refs/heads/main'
      env:
        DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
        DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        DEPLOY_KEY_PASSPHRASE: ${{ secrets.DEPLOY_KEY_PASSPHRASE }}
      run: |
        # Setup SSH
        mkdir -p ~/.ssh
        echo "$DEPLOY_KEY" > ~/.ssh/deploy_key
        chmod 600 ~/.ssh/deploy_key
        ssh-keyscan -H $DEPLOY_HOST >> ~/.ssh/known_hosts
        
        # Start ssh-agent and add key with passphrase
        eval "$(ssh-agent -s)"
        echo "$DEPLOY_KEY_PASSPHRASE" | ssh-add ~/.ssh/deploy_key
        
        # Clear existing files and deploy new ones
        ssh -i ~/.ssh/deploy_key $DEPLOY_USER@$DEPLOY_HOST "rm -rf /usr/share/caddy/*"
        scp -i ~/.ssh/deploy_key -r _site/* $DEPLOY_USER@$DEPLOY_HOST:/tmp/site_temp/
        ssh -i ~/.ssh/deploy_key $DEPLOY_USER@$DEPLOY_HOST "mv /tmp/site_temp/* /usr/share/caddy/ && chgrp -R personal_site /usr/share/caddy/*"